### ISSUE TITLE
Fluid displaced is invisible for fluids with small density value

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#154]
For densities from 0.5 to 1.2, the fluid inside the Fluid Displaced panel is almost invisible: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/03e9feba-3ab9-4e91-aa31-afe2e1125ee2)

![image](https://github.com/phetsims/buoyancy/assets/26031501/2b26e864-c3a0-4f11-af44-4dd16a6cc3ec)

What to do? I think that we can use the same color for all that fluids. Just in the Fluid displaced, use the same color of the fluid used in 1.2 kg/L.

**Comment by zepumph** [comment]
Seems like the main issue is the different backgrounds for the same color, yielding different perceived colors.

Ideas:
* Change the colors (effecting the pool too)
* perhaps just map the color to something with a bigger opacity in the fluid displaced panel.
* change the background of the panel to more closely match the pools

We think it would be good to talk to @DianaTavares

**Comment by DianaTavares** [comment]
> Change the colors (affecting the pool too)

The pool works well, I would like something that affects only the palen.

> Change the background of the panel to more closely match the pools

 I like that it has the same background as the other panels. We can probably change the color of the baker, but I like that is transparent, like the ones in the the labs. 

> perhaps just map the color to something with a bigger opacity in the fluid displaced panel.

I think this is a good idea!! I looked in the color editor to see if it is something to play around with, because now I am worried that for fluids with big density, the fluid gets super dark. But we have room to make the darker fluid in the panel, a little ore dark:

![image](https://github.com/phetsims/buoyancy/assets/26031501/96321a1b-3cd9-4f65-9726-e1149ca354a8)

then I think we are going to be ok. But please, when you make the change, review all the ranges of densities, to ensure that all of them look well.

**Comment by zepumph** [comment]
I committed a change that changed the opacity of beaker color is always 1. It was mostly just to test. Note that when fluid density is at min, the color of the liquid really is just white. Is this enough contrast with the panel background gray?

<img width="1321" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/8db476ba-7bdc-481d-b5ef-297d4fc67d7e">

**Comment by DianaTavares** [comment]
This definitely helps! In the begging of the comment, I describe that the problems go from 0.5 to 1.2 kg/L, 

Now 1.2 looks amazing: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/cc4f1bad-ab58-483b-934a-5c98b37ecad5)

but it still not good below 0.7
![image](https://github.com/phetsims/buoyancy/assets/26031501/ed73d3de-cf64-4a4e-ad11-5cbd3521668a)

Now the range with trouble is smaller! But is not good contrast enough. Can we Hollywood it?   For those values, just leave it the same that 0.7 (or probably from 1).

**Comment by zepumph** [comment]
Ok. I hollywooded below 1kg/L, the color will stay the same as 1kg/L for all densities below that, but only for custom, not other materials.

I still have the "zero opacity" change in for all colors of the beaker, even non custom. Do you want to change this at all? Perhaps only for custom?

Non custom fluids:
<img width="1267" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/7acec78b-668d-4901-beb5-b1b0334b3936">


Min custom fluid holywooding:
<img width="608" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/a617c02a-e29c-41ab-9e17-4de96a3a73b2">

**Comment by DianaTavares** [comment]
I like how it looks in the pictures! The custom looks great! and I am not sure if you are showing the Oil with contrast or with out contrast, but it looks good! 

I leave the issue open because I am not sure if you make the changes already

**Comment by zepumph** [comment]
Yes all changes are pushed. To be totally clear about the change. See above how oil looks in the pool (with opacity) vs in the beaker (no opacity). I removed the opacity for all colors in the beaker, even for non custom materials. It is definitely brighter, but I also kinda like the difference. Play with it a bit in the sim and feel free to close if you like the changes on main right now.

**Comment by samreid** [comment]
@zepumph @DianaTavares and I finished this up and approved it today. Closing.
